<script type="text/javascript" language="JavaScript1.2" src="wfr.js?hash=3a9f496b0ced97f82a60784c65afc1da"></script>
<script type="text/javascript" language="JavaScript1.2" src="rulesFunctions.js?hash=6486699a8219fd518aa901b2f696a003"></script>
<!--XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX//-->
<script type="text/javascript">
try { $mainform().ebfDonwloadStart('tmp/35241231231893000100550010000100311001545536.xml',false); } catch(e) { handleException(e); }
</script>
<script type="text/javascript" src="wfr.js?hash=3a9f496b0ced97f82a60784c65afc1da"></script>
<textarea id="commands">
</textarea>
<script type="text/javascript">
parent.doEval(MM_findObj('commands').value);
$mainform().document._ruleReturn = '';
$mainform().hideWait();
var messagesAsAlert = false;
</script>
