
function HTMLMessage(title,message,timer,type,alignment,confirmButton,cancelButton){this.code=Math.floor(Math.random()*1000000)+1;this.title=title;this.message=message;this.timer=timer;this.cancelButton=(cancelButton!=null)?cancelButton:true;this.cancelButtonDiv=null;this.confirmButton=(confirmButton!=null)?confirmButton:true;this.confirmButtonDiv=null;this.inputText=false;this.inputPlaceholder=null;this.details=null;this.type=type;this.callOk=null;this.callCancel=null;this.alignment=alignment;this.modalDiv=null;this.shown=false;}
HTMLMessage.prototype.name='HTMLMessage';HTMLMessage.prototype.showWarningMessage=function(title,message,timer,alignment){alignment=(this.checkNullOrEmpty(alignment))?messageConfig["position"]:alignment;timer=(timer==0||this.checkNullOrEmpty(timer))?messageConfig["timer"]:timer;this.alignment=alignment;this.title=(title===undefined||title===null)?"":title;this.message=message;this.type="Warning";this.cancelButton=false;this.inputText=false;if(timer){this.confirmButton=false;this.timer=(timer*1000);}
if(!showMessageAsLegacy)this.showWithSweetAlert(this.type.toLowerCase())
else this.showMessage();};HTMLMessage.prototype.showSuccessMessage=function(title,message,timer,alignment){alignment=(this.checkNullOrEmpty(alignment))?messageConfig["position"]:alignment;timer=(timer==0||this.checkNullOrEmpty(timer))?messageConfig["timer"]:timer;this.alignment=alignment;this.title=(title===undefined||title===null)?"":title;this.message=message;this.type="Success";this.cancelButton=false;this.inputText=false;if(timer){this.confirmButton=false;this.timer=(timer*1000);}
if(!showMessageAsLegacy)this.showWithSweetAlert(this.type.toLowerCase())
else this.showMessage();};HTMLMessage.prototype.showInfoMessage=function(title,message,timer,alignment,extended){alignment=(this.checkNullOrEmpty(alignment))?messageConfig["position"]:alignment;timer=(timer==0||this.checkNullOrEmpty(timer))?messageConfig["timer"]:timer;this.alignment=alignment;this.title=(title===undefined||title===null)?"":title;this.message=message;this.type="Info";this.cancelButton=false;this.inputText=false;this.extended=extended;if(timer){this.confirmButton=false;this.timer=(timer*1000);}
if(!showMessageAsLegacy)this.showWithSweetAlert(this.type.toLowerCase());else this.showMessage();};HTMLMessage.prototype.showErrorMessage=function(title,message,timer,details,alignment,extended){alignment=(this.checkNullOrEmpty(alignment))?messageConfig["position"]:alignment;timer=(timer==0||this.checkNullOrEmpty(timer))?messageConfig["timer"]:timer;document.hasRuleErrors=true;document.hasRuleException=true;this.alignment=alignment;this.title=(title===undefined||title===null)?"":title;this.details=(details===undefined||details===null)?"":details;this.message=message;this.type="Error";this.timer=timer;this.inputText=false;this.extended=extended;if(timer){this.timer=(timer*1000);this.confirmButton=false;this.cancelButton=false;}else{this.confirmButton=true;this.cancelButton=false;}
if(!showMessageAsLegacy)this.showWithSweetAlert(this.type.toLowerCase());else this.showMessage();};HTMLMessage.prototype.showPromptMessage=function(title,message,placeholder,funcOk,paramsOk,funcCancel,paramsCancel){this.title=(title===undefined||title===null)?"":title;this.message=message;this.inputPlaceholder=placeholder;this.inputText=true;this.callOk=funcOk;this.callCancel=funcCancel;this.type="Prompt";this.paramsOk=(paramsOk!==undefined&&paramsOk!==null)?paramsOk:[];this.paramsCancel=(paramsCancel!==undefined&&paramsCancel!==null)?paramsCancel:[];if(!showMessageAsLegacy)this.embeddedSweetalert('question',"");else this.showMessage();};HTMLMessage.prototype.showInteractionConfirmMessage=function(title,message,funcOk,paramsOk,funcCancel,paramsCancel,alignment,labelOk,labelCancel){this.alignment=alignment;this.title=(title===undefined||title===null)?"":title;this.message=message;this.inputText=false;this.callOk=funcOk;this.callCancel=funcCancel;this.type="Interaction";this.paramsOk=(paramsOk!==undefined&&paramsOk!==null)?paramsOk:[];this.paramsCancel=(paramsCancel!==undefined&&paramsCancel!==null)?paramsCancel:[];if(!showMessageAsLegacy)this.embeddedSweetalert('warning','interaction');else this.showMessage();if(labelOk&&this.confirmButtonDiv)this.confirmButtonDiv.innerHTML=labelOk;if(labelCancel&&this.cancelButtonDiv)this.cancelButtonDiv.innerHTML=labelCancel;};HTMLMessage.prototype.clickOk=function(div,params,type){if(this.callOk){var paramsTwo;if(params){paramsTwo=new Array();for(i=0;i<params.length;i++){paramsTwo.push(params[i]);}}
if(paramsTwo){if(type==="Prompt"){paramsTwo[0]=this.modalInput.value;}else if(type==="Interaction"){paramsTwo[0]="true";}}
this.closeMessage(div);if(typeof this.callOk==="function"){this.callOk.apply(this,paramsTwo);}else{ebfFlowExecute(this.callOk,paramsTwo);}}else{this.closeMessage(div);}
if(this.callFunctionComponent){if(this.callFunctionComponentParams){this.callFunctionComponent.apply(window,this.callFunctionComponentParams);}else{this.callFunctionComponent.call(window);}}
return true;};HTMLMessage.prototype.clickCancel=function(div,params,type){if(this.callCancel){var paramsTwo;if(params){paramsTwo=new Array();for(i=0;i<params.length;i++){paramsTwo.push(params[i]);}}
if(paramsTwo){if(type==="Prompt"){paramsTwo[0]="";}else if(type==="Interaction"){paramsTwo[0]="false";}}
this.closeMessage(div);if(typeof this.callCancel==="function"){this.callCancel.apply(this,paramsTwo);}else{ebfFlowExecute(this.callCancel,paramsTwo);}}else{this.closeMessage(div);}
return false;};HTMLMessage.prototype.showMessage=function(){var object=this;this.checkBody();try{if((mainform.parent.parent.document.getElementById("tab0")&&this.timer!=0&&this.alignment!=null&&this.alignment.length>0)){var showMsg=new mainform.parent.parent.HTMLMessage(this.title,this.message,this.timer,this.type,this.alignment,this.confirmButton,this.cancelButton);showMsg.showMessage();return;}else if(!isPopup){var locationMessage=$mainform();if(locationMessage)locationMessage.document.body.setAttribute("onunload","$('.message-modal').modal('hide');"+"$('.message-toast').toast('hide');");}}catch(e){}
if(this.alignment&&this.alignment.length>0){this.context=null;this.setAlignment(this.alignmet);if(this.context&&!this.toastDiv){this.toastDiv=this.doc.createElement("div");this.toastDiv.className="toast message-toast";this.toastDiv.id="toast"+this.code;this.toastDiv.setAttribute("role","alert");this.toastDiv.setAttribute("data-autohide","false");this.toastDiv.setAttribute("data-delay","1000");this.toastDiv.style.pointerEvents="all";this.toastHeader=this.doc.createElement("div");this.toastHeader.className="toast-header";this.toastDiv.appendChild(this.toastHeader);if(this.type=="Error"){this.toastHeader.className+=" bg-danger text-white";}else if(this.type=="Warning"){this.toastHeader.className+=" bg-warning text-dark";}else if(this.type=="Prompt"){this.toastHeader.className+=" bg-info text-white";}else if(this.type=="Success"){this.toastHeader.className+=" bg-success text-white";}
if(this.title){this.toastTitle=this.doc.createElement("strong");this.toastTitle.className="mr-auto";this.toastTitle.id="toastTitle"+this.code;this.toastTitle.innerHTML=this.title;if(this.extended===true){this.toastTitle.style.whiteSpace="normal";this.toastTitle.className+=" p-1";}
this.toastHeader.appendChild(this.toastTitle);}
try{if(!this.doc.momentImported){webrun.include("assets/moment.min.js");var lang=resources_locale.replace("_","-");if(lang.indexOf("en")!=-1)lang="en";else if(lang.indexOf("es")!=-1)lang="es";else if(lang.indexOf("fr")!=-1)lang="fr";moment.locale(lang);this.doc.momentImported=true;}
var startTime=moment();this.toastTimestamp=this.doc.createElement("small");this.toastTimestamp.className="pl-2 ml-auto";this.toastTimestamp.innerHTML=moment(startTime).fromNow();this.toastHeader.appendChild(this.toastTimestamp);this.toastTimer=setInterval(function(){if(object.toastTimestamp)object.toastTimestamp.innerHTML=moment(startTime).fromNow();},5000);}catch(e){}
if(this.timer){this.toastProgressBarBase=this.doc.createElement("div");this.toastProgressBarBase.className="progress w-100";this.toastProgressBarBase.style.height="2px";this.toastDiv.appendChild(this.toastProgressBarBase);this.toastHeader.style.borderBottom="0";this.toastProgressBar=this.doc.createElement("div");this.toastProgressBar.className="progress-bar bg-secondary";this.toastProgressBar.id="toastProgressBar"+this.code;this.toastProgressBar.style.width="100%";this.toastProgressBar.setAttribute("role","progressbar");this.toastProgressBar.setAttribute("aria-valuenow","0");this.toastProgressBar.setAttribute("aria-valuemin","0");this.toastProgressBar.setAttribute("aria-valuemax","100");this.toastProgressBarBase.appendChild(this.toastProgressBar);var startTime=new Date();var updateProgressBar=function(){setTimeout(function(){if(object.toastProgressBar){var currentTime=new Date();var elapsedMilliseconds=currentTime-startTime;var percent=100-((elapsedMilliseconds/object.timer)*100);object.toastProgressBar.style.width=percent+"%";object.toastProgressBar.setAttribute("aria-valuenow",percent);if(percent>0)updateProgressBar();}},100);};updateProgressBar();setTimeout(function(){try{object.clickCancel([object.toastDiv],object.paramsCancel,object.type);}catch(e){}},this.timer);}else{this.toastClose=this.doc.createElement("button");this.toastClose.type="button";this.toastClose.id="toastButton"+this.code;this.toastClose.className="ml-2 mb-1 close";this.toastClose.setAttribute("aria-label",getLocaleMessage("LABEL.CLOSE"));this.toastClose.style.outline="0";this.toastClose.style.zIndex="1";this.toastClose.innerHTML='<span aria-hidden="true">&times;</span>';this.toastHeader.appendChild(this.toastClose);this.toastClose.onclick=function(e){e.preventDefault();e.stopPropagation();object.closeMessage();return false;};this.documentKeyDown=this.doc.body.onkeydown;this.doc.body.onkeydown=function(evt){if(evt&&(evt.which===27||evt.code==="Escape")){object.doc.body.onkeydown=object.documentKeyDown;try{object.clickOk([object.modalDiv],object.paramsCancel,object.type);}catch(e){}}};}
if(this.message){this.toastBody=this.doc.createElement("div");this.toastBody.className="toast-body";this.toastBody.innerHTML=this.message.replace(/\n+/g,'<br>');this.toastDiv.appendChild(this.toastBody);}
if(this.callClick){this.toastDiv.onclick=this.callClick;if(this.toastTitle)this.toastTitle.onclick=this.callClick;if(this.toastIcon)this.toastIcon.onclick=this.callClick;if(this.toastTimestamp)this.toastTimestamp.onclick=this.callClick;this.toastDiv.style.cursor="pointer";}
this.context.appendChild(this.toastDiv);$('#toast'+this.code).toast('show');$('#toast'+this.code).on('shown.bs.toast',function(e){object.shown=true;if(object.closeRequired===true){object.closeMessage();}});$('#toast'+this.code).on('hidden.bs.toast',function(){object.shown=false;if(object.toastTimer){clearInterval(object.toastTimer);object.toastTimer=null;}
$(this).toast('dispose');$(this).remove();object.toastDiv=null;object.toastHeader=null;object.toastIcon=null;object.toastTitle=null;object.toastTimestamp=null;object.toastClose=null;});return;}}
var btcontentCancel,btcontentOk;try{btcontentCancel=$mainform().getLocaleMessage("LABEL.CANCEL");}
catch(e){btcontentCancel="Cancel";}
try{btcontentOk=$mainform().getLocaleMessage("LABEL.OK");}
catch(f){btcontentOk="Ok";}
var modal=bootstrapCreateModal();this.modalDiv=modal[0];this.modalDiv.className+=" message-modal";this.shown=true;if(this.closeRequired===true){this.closeMessage();}
$(this.modalDiv).on("hidden.bs.modal",function(e){if(object.shown)object.closeMessage();object.shown=false;});if(this.timer){var modalProgress=document.createElement("div");modalProgress.className="progress w-100";modalProgress.style.height="2px";modal[2].parentElement.insertBefore(modalProgress,modal[2])
this.modalProgressInner=document.createElement("div");this.modalProgressInner.className="progress-bar bg-secondary rounded-0";this.modalProgressInner.id="modalProgressBar"+this.code;this.modalProgressInner.style.width=this.timer+"%";this.modalProgressInner.style.height="2px";this.modalProgressInner.setAttribute("role","progressbar");this.modalProgressInner.setAttribute("aria-valuenow",this.timer.toString());this.modalProgressInner.setAttribute("aria-valuemin","0");this.modalProgressInner.setAttribute("aria-valuemax","100");modalProgress.appendChild(this.modalProgressInner);}
modal[1].className+=" border-bottom-0";modal[1].style.padding="0.8rem";var mediaDiv=document.createElement("div");mediaDiv.className="media px-2 py-1";modal[2].appendChild(mediaDiv);var iconSpan=document.createElement("span");switch(this.type){case"Error":modal[1].className+=" bg-danger";iconSpan.className="fas fa-times text-danger";break;case"Warning":modal[1].className+=" bg-warning";iconSpan.className="fas fa-exclamation-triangle text-warning";break;case"Success":modal[1].className+=" bg-success";iconSpan.className="fas fa-check text-success";break;case"Prompt":case"Interaction":modal[1].className+=" bg-primary";iconSpan.className="fas fa-question-circle text-primary";break;default:modal[1].className+=" bg-dark";break;}
if(iconSpan.className&&iconSpan.className.length>0)
iconSpan.className+=" align-self-start ml-2 mr-4";iconSpan.style.fontSize="3rem";mediaDiv.appendChild(iconSpan);var mediaBody=this.doc.createElement("div");mediaBody.className="media-body";mediaDiv.appendChild(mediaBody);if(this.title&&this.title.length>0){var modalTitle=this.doc.createElement("h5");modalTitle.className="mt-0 text-wrap";modalTitle.style.wordBreak="break-word";modalTitle.innerHTML=this.title;mediaBody.appendChild(modalTitle);}
if(this.message&&this.message.length>0){var modalMessage=this.doc.createElement("p");modalMessage.className="text-wrap";modalMessage.style.wordBreak="break-word";modalMessage.style.wordWrap="break-word";modalMessage.innerHTML=this.message.replace(/\n+/g,'<br>');mediaBody.appendChild(modalMessage);}
if(this.details&&this.details.length>0){var modalDetails=this.doc.createElement("textarea");modalDetails.className="form-control";modalDetails.value=this.details;modalDetails.readOnly=true;modalDetails.style.fontSize="0.7rem";modalDetails.style.minHeight="30vh";mediaBody.appendChild(modalDetails);}
if(this.cancelButton){this.cancelButtonDiv=this.doc.createElement("button");this.cancelButtonDiv.className="btn "+((this.type=="Error")?"btn-danger":(this.type=="Success")?"btn-success":(this.type=="Warning")?"btn-warning text-white":(this.type=="Prompt")?"btn-dark":"btn-primary");this.cancelButtonDiv.type="button";this.cancelButtonDiv.id="modalCancel"+this.code;this.cancelButtonDiv.innerHTML=btcontentCancel;modal[3].appendChild(this.cancelButtonDiv);this.cancelButtonDiv.onclick=function(e){return object.clickCancel([object.modalDiv],object.paramsCancel,object.type);};}
if(this.confirmButton){this.confirmButtonDiv=this.doc.createElement("button");this.confirmButtonDiv.className="btn "+((this.type=="Error")?"btn-danger":(this.type=="Success")?"btn-success":(this.type=="Warning")?"btn-warning text-white":(this.type=="Prompt")?"btn-dark":"btn-primary");this.confirmButtonDiv.type="button";this.confirmButtonDiv.id="modalConfirm"+this.code;this.confirmButtonDiv.innerHTML=btcontentOk;modal[3].appendChild(this.confirmButtonDiv);this.confirmButtonDiv.onclick=function(e){return object.clickOk([object.modalDiv],object.paramsOk,object.type);};}
if(this.inputText){this.modalInput=this.doc.createElement("input");this.modalInput.className="form-control";this.modalInput.type="text";this.modalInput.id="modalInput"+this.code;if(this.inputPlaceholder)this.modalInput.placeholder=this.inputPlaceholder;if(modalMessage)modalMessage.className+=" mb-2";mediaBody.appendChild(this.modalInput);this.modalInput.focus();if(this.confirmButton){this.modalInput.onkeydown=function(evt){if(evt&&(evt.which===13||evt.code==="Enter")){try{object.clickOk([object.modalDiv],object.paramsOk,object.type);}catch(e){}}};}}else{if(this.cancelButton&&this.cancelButtonDiv)this.cancelButtonDiv.focus();else if(this.confirmButton&&this.confirmButtonDiv)this.confirmButtonDiv.focus();}
if(this.cancelButton){this.documentKeyDown=this.doc.body.onkeydown;this.doc.body.onkeydown=function(evt){if(evt&&(evt.which===27||evt.code==="Escape")){object.doc.body.onkeydown=object.documentKeyDown;try{object.clickCancel([object.modalDiv],object.paramsCancel,object.type);}catch(e){}}};}else if(this.confirmButton){this.documentKeyDown=this.doc.body.onkeydown;this.doc.body.onkeydown=function(evt){if(evt&&(evt.which===27||evt.code==="Escape")){object.doc.body.onkeydown=object.documentKeyDown;try{object.clickOk([object.modalDiv],object.paramsCancel,object.type);}catch(e){}}};}
if(this.timer){var startTime=new Date();var updateProgressBar=function(){setTimeout(function(){if(object.modalProgressInner){var currentTime=new Date();var elapsedMilliseconds=currentTime-startTime;var percent=100-((elapsedMilliseconds/object.timer)*100);object.modalProgressInner.style.width=percent+"%";object.modalProgressInner.setAttribute("aria-valuenow",percent);if(percent>0)updateProgressBar();}},100);};updateProgressBar();setTimeout(function(){try{object.clickCancel([object.modalDiv],object.paramsCancel,object.type);}catch(e){}},this.timer);}
var closeAllNotifies=this.closeAllNotifies;};HTMLMessage.prototype.setAlignment=function(){switch(this.alignment.toUpperCase()){case'DT':this.context=this.doc.getElementById("toast-container-tr");if(!this.context){this.context=this.doc.createElement("div");this.context.id="toast-container-tr";this.context.className="toast-container position-fixed mt-3 mr-3";this.context.style.pointerEvents="none";this.context.style.top="0px";this.context.style.right="0px";this.doc.body.appendChild(this.context);}
break;case'ET':this.context=this.doc.getElementById("toast-container-tl");if(!this.context){this.context=this.doc.createElement("div");this.context.id="toast-container-tl";this.context.className="toast-container position-fixed mt-3 ml-3";this.context.style.pointerEvents="none";this.context.style.top="0px";this.context.style.left="0px";this.doc.body.appendChild(this.context);}
break;case'DB':this.context=this.doc.getElementById("toast-container-br");if(!this.context){this.context=this.doc.createElement("div");this.context.id="toast-container-br";this.context.className="toast-container position-fixed mb-3 mr-3";this.context.style.pointerEvents="none";this.context.style.bottom="0px";this.context.style.right="0px";this.doc.body.appendChild(this.context);}
break;case'EB':this.context=this.doc.getElementById("toast-container-bl");if(!this.context){this.context=this.doc.createElement("div");this.context.id="toast-container-bl";this.context.className="toast-container position-fixed mb-3 ml-3";this.context.style.pointerEvents="none";this.context.style.bottom="0px";this.context.style.left="0px";this.doc.body.appendChild(this.context);}
break;}};HTMLMessage.prototype.getParentNotifyDiv=function(alignment){return this.context;};HTMLMessage.prototype.closeAllNotifies=function(){$('.message-modal').modal('hide');$('.message-toast').toast('hide');};HTMLMessage.prototype.closeMessage=function(div){if(!this.shown){this.closeRequired=true;return;}
this.shown=false;this.enabled=false;this.visible=false;if(this.toastDiv){$(this.toastDiv).toast("hide");}else{$(div).modal("hide");}
if(this.documentKeyDown){document.body.onkeydown=this.documentKeyDown;}};HTMLMessage.prototype.showWithSweetAlert=function(type){let object=this;this.checkBody();this.alignment=this.parseAlignment(this.alignment);if((type==="success"||type==="error"||type==="warning"||type==="info")&&this.timer){this.toastMessage(this.title,this.message,type,this.alignment,this.timer);return;}
let textConfirm='Ok',textCancel='Cancel';try{textCancel=$mainform().getLocaleMessage("LABEL.CANCEL");}
catch(e){textCancel="Cancel";}
try{textConfirm=$mainform().getLocaleMessage("LABEL.OK");}
catch(f){textConfirm="Ok";}
let jsonConf={title:this.title,html:this.message&&this.message.length>0?this.message.replace(/(?:\r\n|\r|\n)/g,'<br />'):'',position:this.alignment,confirmButtonText:textConfirm,cancelButtonText:textCancel,showConfirmButton:this.timer?false:true,timer:this.timer,icon:type,heightAuto:false};if(type==='error'&&this.details&&this.details.length>0){jsonConf.input='textarea';jsonConf.inputAttributes={'style':'font-size:1rem;white-space: normal!important;word-break: break-word;overflow-wrap: break-word;','readonly':'true'};jsonConf.inputValue=this.details;}
Swal.fire(jsonConf).then(function(response){if(response.isConfirmed){if(object.callFunctionComponent){if(object.callFunctionComponentParams)
setTimeout(function(){object.callFunctionComponent.apply(this,object.callFunctionComponentParams)},350);else setTimeout(function(){object.callFunctionComponent.call(this);},350);}}});};HTMLMessage.prototype.embeddedSweetalert=function(type,mod){const callbackOk=this.callOk;const callbackCancel=this.callCancel;let paramsOk=this.paramsOk;let paramsCancel=this.paramsCancel;let jsonConf=null;let textConfirm='Ok',textCancel='Cancel';this.message=this.message.replace(/(?:\r\n|\r|\n)/g,'<br />');this.checkBody();try{textCancel=$mainform().getLocaleMessage("LABEL.CANCEL");}
catch(e){textCancel="Cancel";}
try{textConfirm=$mainform().getLocaleMessage("LABEL.OK");}
catch(f){textConfirm="Ok";}
if(mod==='interaction'){jsonConf={title:this.title,html:this.message,icon:type,showCancelButton:true,confirmButtonText:textConfirm,cancelButtonText:textCancel,};}else{jsonConf={title:this.title,html:this.message,icon:type,input:'text',inputPlaceholder:this.inputPlaceholder?this.inputPlaceholder:"",showCancelButton:true,confirmButtonText:textConfirm,cancelButtonText:textCancel,};}
Swal.fire(jsonConf).then(function(response){if(response.isConfirmed){if(callbackOk){var parseParams=new Array();if(paramsOk){for(i=0;i<paramsOk.length;i++){parseParams.push(paramsOk[i]);}}
parseParams[0]=response.value?response.value.toString():"";ebfFlowExecute(callbackOk,parseParams);}}else{if(callbackCancel){var parseParams=new Array();if(paramsCancel){for(i=0;i<paramsCancel.length;i++){parseParams.push(paramsCancel[i]);}}
parseParams[0]=mod==='interaction'?response.isConfirmed.toString():response.value?response.value.toString():"";ebfFlowExecute(callbackCancel,parseParams);}}});};HTMLMessage.prototype.toastMessage=function(title,message,type,position,timer){type=type?type:"success";position=position?position:"center";timer=timer?timer:3000;const Toast=Swal.mixin({toast:true,position:position,showConfirmButton:false,timer:timer,timerProgressBar:true,didOpen:(toast)=>{toast.addEventListener('mouseenter',Swal.stopTimer);toast.addEventListener('mouseleave',Swal.resumeTimer);}});if(message&&message.length>0){title="<span style=\"text-align: left; padding-bottom: 0.25rem; padding-left: 0.25rem; display: flex; flex-direction: column;\">"+"<span style=\"margin-bottom: 0.25rem;\">"+title+"</span>"+"<span style=\"font-size: 1rem; font-weight: normal;\">"+message+"</span>"+"</span>";}else{title="<span style=\"text-align: left;\">"+title+"</span>";}
let object=this;Toast.fire({icon:type,title:title}).then(()=>{if(object.callFunctionComponent&&typeof object.callFunctionComponent==='function'){if(object.callFunctionComponentParams){object.callFunctionComponent.apply(window,object.callFunctionComponentParams);}else{object.callFunctionComponent.call(window);}}});};HTMLMessage.prototype.parseAlignment=function(align){if(align){switch(align){case'DT':align='top-end';break;case'DB':align='bottom-end';break;case'ET':align='top-start';break;case'EB':align='bottom-start';break;default:align='center';break;}}else{align='center';}
return align;};HTMLMessage.prototype.checkBody=function(){try{this.doc=mainform&&mainform.document?mainform.document:document;}
catch(e){this.doc=document;}
if(!this.doc.body)this.doc.writeln("<body></body>");};HTMLMessage.prototype.checkNullOrEmpty=function(value){return(value==='null'||value==null||value===""||value=='undefined'||value===undefined)};